CREATE TABLE ec_cart (
  user_id INT(11) NOT NULL DEFAULT 0,
  item_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item_name VARCHAR(100) NOT NULL DEFAULT 'item_name',
  amount INT(11) NOT NULL,
  in_cart INT(11) NOT NULL DEFAULT 0,
  create_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8 ENGINE=InnoDB;