CREATE TABLE ec_item_master (
  item_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item_name VARCHAR(100) NOT NULL DEFAULT 'item_name',
  price INT(11) NOT NULL,
  img VARCHAR(100) NOT NULL,
  stock INT(11) NOT NULL,
  status INT(11) NOT NULL DEFAULT 0,
  create_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8 ENGINE=InnoDB;
